# Generated by Django 3.0.2 on 2020-01-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('parts', '0002_auto_20200117_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='partvendor',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
    ]
