# Generated by Django 3.0.2 on 2020-01-24 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20200123_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='on_hand',
        ),
        migrations.RemoveField(
            model_name='part',
            name='stocking_cost',
        ),
        migrations.CreateModel(
            name='PartInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_quantity', models.IntegerField(default=0)),
                ('current_on_hand', models.IntegerField(default=0)),
                ('purchase_order_number', models.CharField(max_length=32)),
                ('inventory_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.InventoryLocation')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Part')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PartVendor')),
            ],
        ),
    ]
