# Generated by Django 3.0.2 on 2020-01-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20200124_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='part_images/'),
        ),
        migrations.AlterField(
            model_name='partvendor',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
