# Generated by Django 3.0.2 on 2020-02-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20200131_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='on_hand',
            field=models.IntegerField(default=0),
        ),
    ]
