# Generated by Django 3.2.2 on 2021-05-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_auto_20210514_1340'),
        ('parts', '0008_auto_20200204_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='asset_groups',
            field=models.ManyToManyField(blank=True, to='assets.AssetGroup'),
        ),
    ]
