# Generated by Django 3.0.2 on 2020-01-16 00:59

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='properties',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
