# Generated by Django 3.0.2 on 2020-01-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200116_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproperty',
            name='key_name',
            field=models.CharField(max_length=32),
        ),
    ]
