# Generated by Django 3.0.2 on 2020-01-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20200117_0225'),
        ('assets', '0005_auto_20200116_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='parts',
            field=models.ManyToManyField(to='parts.Part'),
        ),
    ]
