# Generated by Django 3.0.2 on 2020-01-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_partvendor_vendor'),
        ('assets', '0006_asset_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parts',
            field=models.ManyToManyField(blank=True, null=True, to='parts.Part'),
        ),
    ]
