# Generated by Django 3.0.2 on 2020-01-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20200120_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Location'),
        ),
    ]
