# Generated by Django 3.0.2 on 2020-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20200124_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
