# Generated by Django 3.2.2 on 2021-05-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20210513_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetgroup',
            options={'verbose_name_plural': 'Asset Groups'},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='groups',
            new_name='asset_groups',
        ),
    ]
