# Generated by Django 3.0.2 on 2020-01-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0008_auto_20200120_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
                ('wo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.WorkOrderType')),
            ],
        ),
    ]
