# Generated by Django 3.0.2 on 2020-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_auto_20200121_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
