# Generated by Django 3.0.2 on 2020-01-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20200121_1716'),
        ('workorders', '0003_workorder_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='assets.Asset'),
        ),
    ]
