# Generated by Django 3.0.2 on 2020-01-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_auto_20200122_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
