# Generated by Django 3.0.2 on 2020-02-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_workorderpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='number',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
