# Generated by Django 3.0.2 on 2020-02-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_workorder_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='number',
            new_name='wo_id',
        ),
    ]
