# Generated by Django 3.0.2 on 2020-02-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0010_auto_20200204_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='wo_id',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
